// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: album_ratings.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const clearAlbumRating = `-- name: ClearAlbumRating :exec
UPDATE album_ratings SET rating = NULL, updated_at = current_timestamp
WHERE user_id = ? AND album_id = ?
`

type ClearAlbumRatingParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) ClearAlbumRating(ctx context.Context, arg ClearAlbumRatingParams) error {
	_, err := q.db.ExecContext(ctx, clearAlbumRating, arg.UserID, arg.AlbumID)
	return err
}

const getUnratedAlbums = `-- name: GetUnratedAlbums :many
SELECT albums.id, albums.spotify_id, albums.title, albums.created_at, albums.deleted_at, albums.image_url,
    COALESCE((
        SELECT GROUP_CONCAT(a.name, ', ')
        FROM (SELECT DISTINCT ar.id, ar.name FROM album_artists aa JOIN artists ar ON ar.id = aa.artist_id WHERE aa.album_id = albums.id) AS a
    ), '') as artist_names
FROM user_releases
JOIN releases ON releases.id = user_releases.release_id
JOIN albums ON albums.id = releases.album_id
LEFT JOIN album_ratings ON album_ratings.album_id = albums.id AND album_ratings.user_id = user_releases.user_id
WHERE user_releases.user_id = ?
  AND (album_ratings.id IS NULL OR album_ratings.rating IS NULL)
GROUP BY albums.id
ORDER BY MAX(user_releases.added_at) DESC
LIMIT 20
`

type GetUnratedAlbumsRow struct {
	ID          string
	SpotifyID   string
	Title       string
	CreatedAt   time.Time
	DeletedAt   sql.NullTime
	ImageUrl    sql.NullString
	ArtistNames interface{}
}

func (q *Queries) GetUnratedAlbums(ctx context.Context, userID string) ([]GetUnratedAlbumsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnratedAlbums, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnratedAlbumsRow
	for rows.Next() {
		var i GetUnratedAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.Title,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.ImageUrl,
			&i.ArtistNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAlbumRating = `-- name: GetUserAlbumRating :one
select id, user_id, album_id, rating, created_at, updated_at, review from album_ratings
where user_id = ?
and album_id = ?
`

type GetUserAlbumRatingParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) GetUserAlbumRating(ctx context.Context, arg GetUserAlbumRatingParams) (AlbumRating, error) {
	row := q.db.QueryRowContext(ctx, getUserAlbumRating, arg.UserID, arg.AlbumID)
	var i AlbumRating
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Review,
	)
	return i, err
}

const getUserAlbumRatingById = `-- name: GetUserAlbumRatingById :one
select id, user_id, album_id, rating, created_at, updated_at, review from album_ratings
where id = ?
`

func (q *Queries) GetUserAlbumRatingById(ctx context.Context, id string) (AlbumRating, error) {
	row := q.db.QueryRowContext(ctx, getUserAlbumRatingById, id)
	var i AlbumRating
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Review,
	)
	return i, err
}

const getUserAlbumRatings = `-- name: GetUserAlbumRatings :many
select id, user_id, album_id, rating, created_at, updated_at, review from album_ratings
where user_id = ?
`

func (q *Queries) GetUserAlbumRatings(ctx context.Context, userID string) ([]AlbumRating, error) {
	rows, err := q.db.QueryContext(ctx, getUserAlbumRatings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumRating
	for rows.Next() {
		var i AlbumRating
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.Rating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Review,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAlbumRating = `-- name: UpsertAlbumRating :one
INSERT INTO album_ratings (id, user_id, album_id, rating) VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, album_id)
DO UPDATE SET rating = COALESCE(EXCLUDED.rating, rating), review = COALESCE(review, review), updated_at = current_timestamp
RETURNING id, user_id, album_id, rating, created_at, updated_at, review
`

type UpsertAlbumRatingParams struct {
	ID      string
	UserID  string
	AlbumID string
	Rating  sql.NullFloat64
}

func (q *Queries) UpsertAlbumRating(ctx context.Context, arg UpsertAlbumRatingParams) (AlbumRating, error) {
	row := q.db.QueryRowContext(ctx, upsertAlbumRating,
		arg.ID,
		arg.UserID,
		arg.AlbumID,
		arg.Rating,
	)
	var i AlbumRating
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Review,
	)
	return i, err
}

const upsertAlbumReview = `-- name: UpsertAlbumReview :one
INSERT INTO album_ratings (id, user_id, album_id, review) VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, album_id)
DO UPDATE SET review = EXCLUDED.review, updated_at = current_timestamp
RETURNING id, user_id, album_id, rating, created_at, updated_at, review
`

type UpsertAlbumReviewParams struct {
	ID      string
	UserID  string
	AlbumID string
	Review  sql.NullString
}

func (q *Queries) UpsertAlbumReview(ctx context.Context, arg UpsertAlbumReviewParams) (AlbumRating, error) {
	row := q.db.QueryRowContext(ctx, upsertAlbumReview,
		arg.ID,
		arg.UserID,
		arg.AlbumID,
		arg.Review,
	)
	var i AlbumRating
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Review,
	)
	return i, err
}
