// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: album_ratings.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteAlbumRatingLogEntry = `-- name: DeleteAlbumRatingLogEntry :exec
DELETE FROM album_rating_log
WHERE id = ? AND user_id = ?
`

type DeleteAlbumRatingLogEntryParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteAlbumRatingLogEntry(ctx context.Context, arg DeleteAlbumRatingLogEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteAlbumRatingLogEntry, arg.ID, arg.UserID)
	return err
}

const getLatestUserAlbumRating = `-- name: GetLatestUserAlbumRating :one
SELECT id, user_id, album_id, rating, note, created_at FROM album_rating_log
WHERE user_id = ? AND album_id = ?
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestUserAlbumRatingParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) GetLatestUserAlbumRating(ctx context.Context, arg GetLatestUserAlbumRatingParams) (AlbumRatingLog, error) {
	row := q.db.QueryRowContext(ctx, getLatestUserAlbumRating, arg.UserID, arg.AlbumID)
	var i AlbumRatingLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.Rating,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestUserAlbumRatings = `-- name: GetLatestUserAlbumRatings :many
SELECT arl.id, arl.user_id, arl.album_id, arl.rating, arl.note, arl.created_at FROM album_rating_log arl
JOIN (
    SELECT arl2.album_id, MAX(arl2.created_at) AS max_created_at
    FROM album_rating_log arl2
    WHERE arl2.user_id = ?
    GROUP BY arl2.album_id
) latest ON arl.album_id = latest.album_id AND arl.created_at = latest.max_created_at
WHERE arl.user_id = ?
`

type GetLatestUserAlbumRatingsParams struct {
	UserID   string
	UserID_2 string
}

func (q *Queries) GetLatestUserAlbumRatings(ctx context.Context, arg GetLatestUserAlbumRatingsParams) ([]AlbumRatingLog, error) {
	rows, err := q.db.QueryContext(ctx, getLatestUserAlbumRatings, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumRatingLog
	for rows.Next() {
		var i AlbumRatingLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.Rating,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnratedAlbums = `-- name: GetUnratedAlbums :many
SELECT albums.id, albums.spotify_id, albums.title, albums.created_at, albums.deleted_at, albums.image_url,
    COALESCE((
        SELECT GROUP_CONCAT(a.name, ', ')
        FROM (SELECT DISTINCT ar.id, ar.name FROM album_artists aa JOIN artists ar ON ar.id = aa.artist_id WHERE aa.album_id = albums.id) AS a
    ), '') as artist_names
FROM user_releases
JOIN releases ON releases.id = user_releases.release_id
JOIN albums ON albums.id = releases.album_id
LEFT JOIN (
    SELECT arl.album_id, arl.user_id
    FROM album_rating_log arl
    JOIN (
        SELECT arl2.album_id, MAX(arl2.created_at) AS max_created_at
        FROM album_rating_log arl2
        WHERE arl2.user_id = ?
        GROUP BY arl2.album_id
    ) latest ON arl.album_id = latest.album_id AND arl.created_at = latest.max_created_at
    WHERE arl.user_id = ?
) latest_rating ON latest_rating.album_id = albums.id AND latest_rating.user_id = user_releases.user_id
LEFT JOIN track_plays ON track_plays.album_id = albums.id AND track_plays.user_id = user_releases.user_id
WHERE user_releases.user_id = ?
  AND latest_rating.album_id IS NULL
GROUP BY albums.id
ORDER BY MAX(track_plays.played_at) DESC NULLS LAST, MAX(user_releases.added_at) DESC
LIMIT 20
`

type GetUnratedAlbumsParams struct {
	UserID   string
	UserID_2 string
	UserID_3 string
}

type GetUnratedAlbumsRow struct {
	ID          string
	SpotifyID   string
	Title       string
	CreatedAt   time.Time
	DeletedAt   sql.NullTime
	ImageUrl    sql.NullString
	ArtistNames interface{}
}

func (q *Queries) GetUnratedAlbums(ctx context.Context, arg GetUnratedAlbumsParams) ([]GetUnratedAlbumsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnratedAlbums, arg.UserID, arg.UserID_2, arg.UserID_3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnratedAlbumsRow
	for rows.Next() {
		var i GetUnratedAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.Title,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.ImageUrl,
			&i.ArtistNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAlbumRatingLog = `-- name: GetUserAlbumRatingLog :many
SELECT id, user_id, album_id, rating, note, created_at FROM album_rating_log
WHERE user_id = ? AND album_id = ?
ORDER BY created_at DESC
`

type GetUserAlbumRatingLogParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) GetUserAlbumRatingLog(ctx context.Context, arg GetUserAlbumRatingLogParams) ([]AlbumRatingLog, error) {
	rows, err := q.db.QueryContext(ctx, getUserAlbumRatingLog, arg.UserID, arg.AlbumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumRatingLog
	for rows.Next() {
		var i AlbumRatingLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.Rating,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAlbumRatingLogEntry = `-- name: InsertAlbumRatingLogEntry :one
INSERT INTO album_rating_log (id, user_id, album_id, rating, note, created_at)
VALUES (?, ?, ?, ?, ?, current_timestamp)
RETURNING id, user_id, album_id, rating, note, created_at
`

type InsertAlbumRatingLogEntryParams struct {
	ID      string
	UserID  string
	AlbumID string
	Rating  float64
	Note    sql.NullString
}

func (q *Queries) InsertAlbumRatingLogEntry(ctx context.Context, arg InsertAlbumRatingLogEntryParams) (AlbumRatingLog, error) {
	row := q.db.QueryRowContext(ctx, insertAlbumRatingLogEntry,
		arg.ID,
		arg.UserID,
		arg.AlbumID,
		arg.Rating,
		arg.Note,
	)
	var i AlbumRatingLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.Rating,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
