// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: album_genres.sql

package sqlc

import (
	"context"
	"strings"
)

const deleteAlbumGenresByAlbumId = `-- name: DeleteAlbumGenresByAlbumId :exec
DELETE FROM album_genres WHERE album_id = ?
`

func (q *Queries) DeleteAlbumGenresByAlbumId(ctx context.Context, albumID string) error {
	_, err := q.db.ExecContext(ctx, deleteAlbumGenresByAlbumId, albumID)
	return err
}

const getAlbumGenresByAlbumIds = `-- name: GetAlbumGenresByAlbumIds :many
SELECT album_id, genre_id, genre_label FROM album_genres
WHERE album_id IN (/*SLICE:album_ids*/?)
ORDER BY genre_label
`

type GetAlbumGenresByAlbumIdsRow struct {
	AlbumID    string
	GenreID    string
	GenreLabel string
}

func (q *Queries) GetAlbumGenresByAlbumIds(ctx context.Context, albumIds []string) ([]GetAlbumGenresByAlbumIdsRow, error) {
	query := getAlbumGenresByAlbumIds
	var queryParams []interface{}
	if len(albumIds) > 0 {
		for _, v := range albumIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:album_ids*/?", strings.Repeat(",?", len(albumIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:album_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlbumGenresByAlbumIdsRow
	for rows.Next() {
		var i GetAlbumGenresByAlbumIdsRow
		if err := rows.Scan(&i.AlbumID, &i.GenreID, &i.GenreLabel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnrichedAlbumIds = `-- name: GetEnrichedAlbumIds :many
SELECT album_id FROM album_genre_enrichment
WHERE album_id IN (/*SLICE:album_ids*/?)
`

func (q *Queries) GetEnrichedAlbumIds(ctx context.Context, albumIds []string) ([]string, error) {
	query := getEnrichedAlbumIds
	var queryParams []interface{}
	if len(albumIds) > 0 {
		for _, v := range albumIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:album_ids*/?", strings.Repeat(",?", len(albumIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:album_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var album_id string
		if err := rows.Scan(&album_id); err != nil {
			return nil, err
		}
		items = append(items, album_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlbumGenreEnriched = `-- name: MarkAlbumGenreEnriched :exec
INSERT INTO album_genre_enrichment (album_id) VALUES (?)
ON CONFLICT (album_id) DO UPDATE SET enriched_at = CURRENT_TIMESTAMP
`

func (q *Queries) MarkAlbumGenreEnriched(ctx context.Context, albumID string) error {
	_, err := q.db.ExecContext(ctx, markAlbumGenreEnriched, albumID)
	return err
}

const upsertAlbumGenre = `-- name: UpsertAlbumGenre :exec
INSERT INTO album_genres (id, album_id, genre_id, genre_label) VALUES (?, ?, ?, ?)
ON CONFLICT (album_id, genre_id) DO UPDATE SET genre_label = excluded.genre_label
`

type UpsertAlbumGenreParams struct {
	ID         string
	AlbumID    string
	GenreID    string
	GenreLabel string
}

func (q *Queries) UpsertAlbumGenre(ctx context.Context, arg UpsertAlbumGenreParams) error {
	_, err := q.db.ExecContext(ctx, upsertAlbumGenre,
		arg.ID,
		arg.AlbumID,
		arg.GenreID,
		arg.GenreLabel,
	)
	return err
}
