// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: album_rating_state.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getAlbumRatingState = `-- name: GetAlbumRatingState :one
SELECT id, user_id, album_id, state, created_at, updated_at FROM album_rating_state
WHERE user_id = ? AND album_id = ?
`

type GetAlbumRatingStateParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) GetAlbumRatingState(ctx context.Context, arg GetAlbumRatingStateParams) (AlbumRatingState, error) {
	row := q.db.QueryRowContext(ctx, getAlbumRatingState, arg.UserID, arg.AlbumID)
	var i AlbumRatingState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllAlbumRatingStates = `-- name: GetAllAlbumRatingStates :many
SELECT id, user_id, album_id, state, created_at, updated_at FROM album_rating_state
WHERE user_id = ?
`

func (q *Queries) GetAllAlbumRatingStates(ctx context.Context, userID string) ([]AlbumRatingState, error) {
	rows, err := q.db.QueryContext(ctx, getAllAlbumRatingStates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumRatingState
	for rows.Next() {
		var i AlbumRatingState
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProvisionalAlbums = `-- name: GetProvisionalAlbums :many
SELECT
    albums.id,
    albums.spotify_id,
    albums.title,
    albums.image_url,
    COALESCE((
        SELECT GROUP_CONCAT(ar.name, ', ')
        FROM (SELECT DISTINCT ar2.id, ar2.name FROM album_artists aa JOIN artists ar2 ON ar2.id = aa.artist_id WHERE aa.album_id = albums.id) AS ar
    ), '') AS artist_names,
    ars.state,
    COALESCE(arl.rating, 0) AS latest_rating,
    CASE WHEN arl.rating IS NULL THEN 0 ELSE 1 END AS has_rating
FROM album_rating_state ars
JOIN albums ON albums.id = ars.album_id
LEFT JOIN (
    SELECT arl2.album_id, arl2.rating
    FROM album_rating_log arl2
    JOIN (
        SELECT arl3.album_id, MAX(arl3.created_at) AS max_created_at
        FROM album_rating_log arl3
        WHERE arl3.user_id = ?
        GROUP BY arl3.album_id
    ) latest ON arl2.album_id = latest.album_id AND arl2.created_at = latest.max_created_at
    WHERE arl2.user_id = ?
) arl ON arl.album_id = ars.album_id
WHERE ars.user_id = ?
  AND ars.state = 'provisional'
ORDER BY ars.updated_at ASC
`

type GetProvisionalAlbumsParams struct {
	UserID   string
	UserID_2 string
	UserID_3 string
}

type GetProvisionalAlbumsRow struct {
	ID           string
	SpotifyID    string
	Title        string
	ImageUrl     sql.NullString
	ArtistNames  interface{}
	State        string
	LatestRating float64
	HasRating    int64
}

// A provisional album may have zero rows in album_rating_log (e.g. rows
// promoted into 'provisional' by the retired-stalled backfill). The LEFT JOIN
// onto the latest-rating subquery yields NULL for those rows; we cannot
// project arl.rating directly because sqlc infers a non-nullable Go float64
// from album_rating_log.rating's NOT NULL schema. The has_rating flag carries
// log-row presence to the application; latest_rating is COALESCE'd to 0 for
// albums with no log row so the column is never NULL on the wire.
func (q *Queries) GetProvisionalAlbums(ctx context.Context, arg GetProvisionalAlbumsParams) ([]GetProvisionalAlbumsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProvisionalAlbums, arg.UserID, arg.UserID_2, arg.UserID_3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProvisionalAlbumsRow
	for rows.Next() {
		var i GetProvisionalAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.Title,
			&i.ImageUrl,
			&i.ArtistNames,
			&i.State,
			&i.LatestRating,
			&i.HasRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAlbumRatingState = `-- name: InsertAlbumRatingState :one
INSERT INTO album_rating_state (id, user_id, album_id, state, created_at, updated_at)
VALUES (?, ?, ?, ?, current_timestamp, current_timestamp)
RETURNING id, user_id, album_id, state, created_at, updated_at
`

type InsertAlbumRatingStateParams struct {
	ID      string
	UserID  string
	AlbumID string
	State   string
}

func (q *Queries) InsertAlbumRatingState(ctx context.Context, arg InsertAlbumRatingStateParams) (AlbumRatingState, error) {
	row := q.db.QueryRowContext(ctx, insertAlbumRatingState,
		arg.ID,
		arg.UserID,
		arg.AlbumID,
		arg.State,
	)
	var i AlbumRatingState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAlbumRatingState = `-- name: UpdateAlbumRatingState :one
UPDATE album_rating_state
SET state = ?, updated_at = current_timestamp
WHERE user_id = ? AND album_id = ?
RETURNING id, user_id, album_id, state, created_at, updated_at
`

type UpdateAlbumRatingStateParams struct {
	State   string
	UserID  string
	AlbumID string
}

func (q *Queries) UpdateAlbumRatingState(ctx context.Context, arg UpdateAlbumRatingStateParams) (AlbumRatingState, error) {
	row := q.db.QueryRowContext(ctx, updateAlbumRatingState, arg.State, arg.UserID, arg.AlbumID)
	var i AlbumRatingState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
