// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: album_notes.sql

package sqlc

import (
	"context"
	"strings"
)

const getAlbumNote = `-- name: GetAlbumNote :one
SELECT id, user_id, album_id, content, updated_at FROM album_notes WHERE user_id = ? AND album_id = ?
`

type GetAlbumNoteParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) GetAlbumNote(ctx context.Context, arg GetAlbumNoteParams) (AlbumNote, error) {
	row := q.db.QueryRowContext(ctx, getAlbumNote, arg.UserID, arg.AlbumID)
	var i AlbumNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.Content,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlbumNotesByAlbumIds = `-- name: GetAlbumNotesByAlbumIds :many
SELECT id, user_id, album_id, content, updated_at FROM album_notes
WHERE user_id = ? AND album_id IN (/*SLICE:album_ids*/?)
`

type GetAlbumNotesByAlbumIdsParams struct {
	UserID   string
	AlbumIds []string
}

func (q *Queries) GetAlbumNotesByAlbumIds(ctx context.Context, arg GetAlbumNotesByAlbumIdsParams) ([]AlbumNote, error) {
	query := getAlbumNotesByAlbumIds
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.AlbumIds) > 0 {
		for _, v := range arg.AlbumIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:album_ids*/?", strings.Repeat(",?", len(arg.AlbumIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:album_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumNote
	for rows.Next() {
		var i AlbumNote
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.Content,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAlbumNote = `-- name: UpsertAlbumNote :one
INSERT INTO album_notes (id, user_id, album_id, content, updated_at)
VALUES (?, ?, ?, ?, current_timestamp)
ON CONFLICT(user_id, album_id) DO UPDATE SET
    content = excluded.content,
    updated_at = current_timestamp
RETURNING id, user_id, album_id, content, updated_at
`

type UpsertAlbumNoteParams struct {
	ID      string
	UserID  string
	AlbumID string
	Content string
}

func (q *Queries) UpsertAlbumNote(ctx context.Context, arg UpsertAlbumNoteParams) (AlbumNote, error) {
	row := q.db.QueryRowContext(ctx, upsertAlbumNote,
		arg.ID,
		arg.UserID,
		arg.AlbumID,
		arg.Content,
	)
	var i AlbumNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.Content,
		&i.UpdatedAt,
	)
	return i, err
}
