// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: albums.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const createAlbum = `-- name: CreateAlbum :exec
INSERT INTO albums (id, spotify_id, title, image_url) VALUES (?, ?, ?, ?)
`

type CreateAlbumParams struct {
	ID        string
	SpotifyID string
	Title     string
	ImageUrl  sql.NullString
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) error {
	_, err := q.db.ExecContext(ctx, createAlbum,
		arg.ID,
		arg.SpotifyID,
		arg.Title,
		arg.ImageUrl,
	)
	return err
}

const getAlbum = `-- name: GetAlbum :one
SELECT id, spotify_id, title, created_at, deleted_at, image_url FROM albums WHERE id = ?
`

func (q *Queries) GetAlbum(ctx context.Context, id string) (Album, error) {
	row := q.db.QueryRowContext(ctx, getAlbum, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Title,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.ImageUrl,
	)
	return i, err
}

const getAlbumBySpotifyId = `-- name: GetAlbumBySpotifyId :one
SELECT id, spotify_id, title, created_at, deleted_at, image_url FROM albums WHERE spotify_id = ?
`

func (q *Queries) GetAlbumBySpotifyId(ctx context.Context, spotifyID string) (Album, error) {
	row := q.db.QueryRowContext(ctx, getAlbumBySpotifyId, spotifyID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Title,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.ImageUrl,
	)
	return i, err
}

const getAlbumsByIDs = `-- name: GetAlbumsByIDs :many
SELECT id, spotify_id, title, created_at, deleted_at, image_url FROM albums WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetAlbumsByIDs(ctx context.Context, ids []string) ([]Album, error) {
	query := getAlbumsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.Title,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateAlbum = `-- name: GetOrCreateAlbum :one
INSERT INTO albums (id, spotify_id, title, image_url) VALUES (?, ?, ?, ?)
ON CONFLICT (spotify_id)
DO UPDATE SET image_url = excluded.image_url
RETURNING id, spotify_id, title, created_at, deleted_at, image_url
`

type GetOrCreateAlbumParams struct {
	ID        string
	SpotifyID string
	Title     string
	ImageUrl  sql.NullString
}

func (q *Queries) GetOrCreateAlbum(ctx context.Context, arg GetOrCreateAlbumParams) (Album, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateAlbum,
		arg.ID,
		arg.SpotifyID,
		arg.Title,
		arg.ImageUrl,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Title,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.ImageUrl,
	)
	return i, err
}
