// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: crates.sql

package sqlc

import (
	"context"
	"time"
)

const deleteCrate = `-- name: DeleteCrate :exec
DELETE FROM crates WHERE id = ? AND user_id = ?
`

type DeleteCrateParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteCrate(ctx context.Context, arg DeleteCrateParams) error {
	_, err := q.db.ExecContext(ctx, deleteCrate, arg.ID, arg.UserID)
	return err
}

const deleteCrateAlbum = `-- name: DeleteCrateAlbum :exec
DELETE FROM crate_albums WHERE crate_id = ? AND album_id = ?
`

type DeleteCrateAlbumParams struct {
	CrateID string
	AlbumID string
}

func (q *Queries) DeleteCrateAlbum(ctx context.Context, arg DeleteCrateAlbumParams) error {
	_, err := q.db.ExecContext(ctx, deleteCrateAlbum, arg.CrateID, arg.AlbumID)
	return err
}

const getCrate = `-- name: GetCrate :one
SELECT c.id, c.name, c.created_at
FROM crates c
WHERE c.id = ? AND c.user_id = ?
`

type GetCrateParams struct {
	ID     string
	UserID string
}

type GetCrateRow struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

func (q *Queries) GetCrate(ctx context.Context, arg GetCrateParams) (GetCrateRow, error) {
	row := q.db.QueryRowContext(ctx, getCrate, arg.ID, arg.UserID)
	var i GetCrateRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getCrateAlbumIDs = `-- name: GetCrateAlbumIDs :many
SELECT album_id FROM crate_albums WHERE crate_id = ? ORDER BY added_at DESC
`

func (q *Queries) GetCrateAlbumIDs(ctx context.Context, crateID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCrateAlbumIDs, crateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var album_id string
		if err := rows.Scan(&album_id); err != nil {
			return nil, err
		}
		items = append(items, album_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCrate = `-- name: InsertCrate :one
INSERT INTO crates (id, user_id, name) VALUES (?, ?, ?) RETURNING id, user_id, name, created_at
`

type InsertCrateParams struct {
	ID     string
	UserID string
	Name   string
}

func (q *Queries) InsertCrate(ctx context.Context, arg InsertCrateParams) (Crate, error) {
	row := q.db.QueryRowContext(ctx, insertCrate, arg.ID, arg.UserID, arg.Name)
	var i Crate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const insertCrateAlbum = `-- name: InsertCrateAlbum :exec
INSERT INTO crate_albums (id, crate_id, album_id) VALUES (?, ?, ?) ON CONFLICT(crate_id, album_id) DO NOTHING
`

type InsertCrateAlbumParams struct {
	ID      string
	CrateID string
	AlbumID string
}

func (q *Queries) InsertCrateAlbum(ctx context.Context, arg InsertCrateAlbumParams) error {
	_, err := q.db.ExecContext(ctx, insertCrateAlbum, arg.ID, arg.CrateID, arg.AlbumID)
	return err
}

const listCrates = `-- name: ListCrates :many
SELECT c.id, c.name, COUNT(ca.id) AS album_count, c.created_at
FROM crates c
LEFT JOIN crate_albums ca ON ca.crate_id = c.id
WHERE c.user_id = ?
GROUP BY c.id
ORDER BY c.name COLLATE NOCASE ASC
`

type ListCratesRow struct {
	ID         string
	Name       string
	AlbumCount int64
	CreatedAt  time.Time
}

func (q *Queries) ListCrates(ctx context.Context, userID string) ([]ListCratesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCrates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCratesRow
	for rows.Next() {
		var i ListCratesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AlbumCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
