// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package sqlc

import (
	"context"
	"database/sql"

	"shmoopicks/src/internal/core/db/models"
)

const createFeed = `-- name: CreateFeed :one
insert into feeds (user_id, kind)
values (?, ?)
returning id, user_id, kind, created_at, last_sync_completed_at, last_sync_started_at, last_sync_status
`

type CreateFeedParams struct {
	UserID string
	Kind   models.FeedKind
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed, arg.UserID, arg.Kind)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.CreatedAt,
		&i.LastSyncCompletedAt,
		&i.LastSyncStartedAt,
		&i.LastSyncStatus,
	)
	return i, err
}

const getFeedByID = `-- name: GetFeedByID :one
select id, user_id, kind, created_at, last_sync_completed_at, last_sync_started_at, last_sync_status from feeds where id = ? and user_id = ?
`

type GetFeedByIDParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetFeedByID(ctx context.Context, arg GetFeedByIDParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByID, arg.ID, arg.UserID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.CreatedAt,
		&i.LastSyncCompletedAt,
		&i.LastSyncStartedAt,
		&i.LastSyncStatus,
	)
	return i, err
}

const getFeedsByUserId = `-- name: GetFeedsByUserId :many
select id, user_id, kind, created_at, last_sync_completed_at, last_sync_started_at, last_sync_status from feeds where user_id = ?
`

func (q *Queries) GetFeedsByUserId(ctx context.Context, userID string) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.CreatedAt,
			&i.LastSyncCompletedAt,
			&i.LastSyncStartedAt,
			&i.LastSyncStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaleFeedsBatch = `-- name: GetStaleFeedsBatch :many
SELECT id, user_id, kind, created_at, last_sync_completed_at, last_sync_started_at, last_sync_status FROM feeds
WHERE last_sync_completed_at IS NOT NULL
AND last_sync_completed_at < datetime('now', ?)
AND kind = ?
ORDER BY last_sync_completed_at ASC
LIMIT 10
`

type GetStaleFeedsBatchParams struct {
	Datetime interface{}
	Kind     models.FeedKind
}

func (q *Queries) GetStaleFeedsBatch(ctx context.Context, arg GetStaleFeedsBatchParams) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getStaleFeedsBatch, arg.Datetime, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.CreatedAt,
			&i.LastSyncCompletedAt,
			&i.LastSyncStartedAt,
			&i.LastSyncStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeed = `-- name: UpdateFeed :one
UPDATE feeds
SET last_sync_completed_at = COALESCE(?, last_sync_completed_at),
    last_sync_started_at = COALESCE(?, last_sync_started_at),
    last_sync_status = COALESCE(?, last_sync_status)
WHERE id = ?
RETURNING id, user_id, kind, created_at, last_sync_completed_at, last_sync_started_at, last_sync_status
`

type UpdateFeedParams struct {
	LastSyncCompletedAt sql.NullTime
	LastSyncStartedAt   sql.NullTime
	LastSyncStatus      models.FeedSyncStatus
	ID                  string
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, updateFeed,
		arg.LastSyncCompletedAt,
		arg.LastSyncStartedAt,
		arg.LastSyncStatus,
		arg.ID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.CreatedAt,
		&i.LastSyncCompletedAt,
		&i.LastSyncStartedAt,
		&i.LastSyncStatus,
	)
	return i, err
}

const upsertFeed = `-- name: UpsertFeed :one
INSERT INTO feeds (id, user_id, kind)
VALUES (?, ?, ?)
ON CONFLICT (user_id, kind) DO UPDATE SET
    user_id = excluded.user_id,
    kind = excluded.kind
RETURNING id, user_id, kind, created_at, last_sync_completed_at, last_sync_started_at, last_sync_status
`

type UpsertFeedParams struct {
	ID     string
	UserID string
	Kind   models.FeedKind
}

func (q *Queries) UpsertFeed(ctx context.Context, arg UpsertFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, upsertFeed, arg.ID, arg.UserID, arg.Kind)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.CreatedAt,
		&i.LastSyncCompletedAt,
		&i.LastSyncStartedAt,
		&i.LastSyncStatus,
	)
	return i, err
}
