// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/alecdray/wax/src/internal/core/db/models"
)

const createFeed = `-- name: CreateFeed :one
insert into feeds (user_id, kind)
values (?, ?)
returning id, user_id, kind, created_at, last_sync_completed_at, last_sync_started_at, last_sync_status, source_ref, next_sync_at, consecutive_failures
`

type CreateFeedParams struct {
	UserID string
	Kind   models.FeedKind
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed, arg.UserID, arg.Kind)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.CreatedAt,
		&i.LastSyncCompletedAt,
		&i.LastSyncStartedAt,
		&i.LastSyncStatus,
		&i.SourceRef,
		&i.NextSyncAt,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds WHERE id = ?
`

func (q *Queries) DeleteFeed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, id)
	return err
}

const getDueFeedsBatch = `-- name: GetDueFeedsBatch :many
SELECT id, user_id, kind, created_at, last_sync_completed_at, last_sync_started_at, last_sync_status, source_ref, next_sync_at, consecutive_failures FROM feeds
WHERE kind = ?
AND (next_sync_at IS NULL OR next_sync_at <= datetime('now'))
ORDER BY next_sync_at ASC
LIMIT 10
`

// Feeds of a kind that are due to sync: next_sync_at has passed, or is NULL
// (never scheduled, so sync immediately). A just-failed feed has next_sync_at
// pushed into the future by its backoff, so it is not re-picked until then.
// Soonest-due first; NULL (never scheduled) sorts ahead of the rest.
func (q *Queries) GetDueFeedsBatch(ctx context.Context, kind models.FeedKind) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getDueFeedsBatch, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.CreatedAt,
			&i.LastSyncCompletedAt,
			&i.LastSyncStartedAt,
			&i.LastSyncStatus,
			&i.SourceRef,
			&i.NextSyncAt,
			&i.ConsecutiveFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedByID = `-- name: GetFeedByID :one
select id, user_id, kind, created_at, last_sync_completed_at, last_sync_started_at, last_sync_status, source_ref, next_sync_at, consecutive_failures from feeds where id = ? and user_id = ?
`

type GetFeedByIDParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetFeedByID(ctx context.Context, arg GetFeedByIDParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByID, arg.ID, arg.UserID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.CreatedAt,
		&i.LastSyncCompletedAt,
		&i.LastSyncStartedAt,
		&i.LastSyncStatus,
		&i.SourceRef,
		&i.NextSyncAt,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const getFeedsByUserId = `-- name: GetFeedsByUserId :many
select id, user_id, kind, created_at, last_sync_completed_at, last_sync_started_at, last_sync_status, source_ref, next_sync_at, consecutive_failures from feeds where user_id = ?
`

func (q *Queries) GetFeedsByUserId(ctx context.Context, userID string) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.CreatedAt,
			&i.LastSyncCompletedAt,
			&i.LastSyncStartedAt,
			&i.LastSyncStatus,
			&i.SourceRef,
			&i.NextSyncAt,
			&i.ConsecutiveFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncableRadarFeeds = `-- name: GetSyncableRadarFeeds :many
SELECT id, user_id, kind, created_at, last_sync_completed_at, last_sync_started_at, last_sync_status, source_ref, next_sync_at, consecutive_failures FROM feeds
WHERE kind = 'spotify_radar' AND source_ref IS NOT NULL
AND (next_sync_at IS NULL OR next_sync_at <= datetime('now'))
ORDER BY next_sync_at ASC
LIMIT 10
`

// Radar inbox feeds due to sync: those with a playlist handle whose next_sync_at
// has passed (or is NULL). Same due-ness rule as GetDueFeedsBatch, so a failed
// radar feed backs off instead of being re-read every tick.
func (q *Queries) GetSyncableRadarFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getSyncableRadarFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.CreatedAt,
			&i.LastSyncCompletedAt,
			&i.LastSyncStartedAt,
			&i.LastSyncStatus,
			&i.SourceRef,
			&i.NextSyncAt,
			&i.ConsecutiveFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeedSourceRef = `-- name: SetFeedSourceRef :exec
UPDATE feeds SET source_ref = ? WHERE id = ?
`

type SetFeedSourceRefParams struct {
	SourceRef sql.NullString
	ID        string
}

// Sets (or, with NULL, clears) a feed's external source handle.
func (q *Queries) SetFeedSourceRef(ctx context.Context, arg SetFeedSourceRefParams) error {
	_, err := q.db.ExecContext(ctx, setFeedSourceRef, arg.SourceRef, arg.ID)
	return err
}

const updateFeed = `-- name: UpdateFeed :one
UPDATE feeds
SET last_sync_completed_at = COALESCE(?, last_sync_completed_at),
    last_sync_started_at = COALESCE(?, last_sync_started_at),
    last_sync_status = COALESCE(?, last_sync_status),
    next_sync_at = ?,
    consecutive_failures = ?
WHERE id = ?
RETURNING id, user_id, kind, created_at, last_sync_completed_at, last_sync_started_at, last_sync_status, source_ref, next_sync_at, consecutive_failures
`

type UpdateFeedParams struct {
	LastSyncCompletedAt sql.NullTime
	LastSyncStartedAt   sql.NullTime
	LastSyncStatus      models.FeedSyncStatus
	NextSyncAt          sql.NullTime
	ConsecutiveFailures int64
	ID                  string
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, updateFeed,
		arg.LastSyncCompletedAt,
		arg.LastSyncStartedAt,
		arg.LastSyncStatus,
		arg.NextSyncAt,
		arg.ConsecutiveFailures,
		arg.ID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.CreatedAt,
		&i.LastSyncCompletedAt,
		&i.LastSyncStartedAt,
		&i.LastSyncStatus,
		&i.SourceRef,
		&i.NextSyncAt,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const upsertFeed = `-- name: UpsertFeed :one
INSERT INTO feeds (id, user_id, kind)
VALUES (?, ?, ?)
ON CONFLICT (user_id, kind) DO UPDATE SET
    user_id = excluded.user_id,
    kind = excluded.kind
RETURNING id, user_id, kind, created_at, last_sync_completed_at, last_sync_started_at, last_sync_status, source_ref, next_sync_at, consecutive_failures
`

type UpsertFeedParams struct {
	ID     string
	UserID string
	Kind   models.FeedKind
}

func (q *Queries) UpsertFeed(ctx context.Context, arg UpsertFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, upsertFeed, arg.ID, arg.UserID, arg.Kind)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.CreatedAt,
		&i.LastSyncCompletedAt,
		&i.LastSyncStartedAt,
		&i.LastSyncStatus,
		&i.SourceRef,
		&i.NextSyncAt,
		&i.ConsecutiveFailures,
	)
	return i, err
}
