// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: labels.sql

package sqlc

import (
	"context"
	"strings"
)

const createAlbumGenre = `-- name: CreateAlbumGenre :one
INSERT INTO album_genres (id, user_id, album_id, genre_id, genre_label)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (user_id, album_id, genre_id) DO UPDATE SET genre_label = excluded.genre_label
RETURNING id, user_id, album_id, genre_id, genre_label, created_at
`

type CreateAlbumGenreParams struct {
	ID         string
	UserID     string
	AlbumID    string
	GenreID    string
	GenreLabel string
}

func (q *Queries) CreateAlbumGenre(ctx context.Context, arg CreateAlbumGenreParams) (AlbumGenre, error) {
	row := q.db.QueryRowContext(ctx, createAlbumGenre,
		arg.ID,
		arg.UserID,
		arg.AlbumID,
		arg.GenreID,
		arg.GenreLabel,
	)
	var i AlbumGenre
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.GenreID,
		&i.GenreLabel,
		&i.CreatedAt,
	)
	return i, err
}

const createAlbumMood = `-- name: CreateAlbumMood :one
INSERT INTO album_moods (id, user_id, album_id, mood)
VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, album_id, mood) DO UPDATE SET mood = mood
RETURNING id, user_id, album_id, mood, created_at
`

type CreateAlbumMoodParams struct {
	ID      string
	UserID  string
	AlbumID string
	Mood    string
}

func (q *Queries) CreateAlbumMood(ctx context.Context, arg CreateAlbumMoodParams) (AlbumMood, error) {
	row := q.db.QueryRowContext(ctx, createAlbumMood,
		arg.ID,
		arg.UserID,
		arg.AlbumID,
		arg.Mood,
	)
	var i AlbumMood
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.Mood,
		&i.CreatedAt,
	)
	return i, err
}

const createAlbumUserTag = `-- name: CreateAlbumUserTag :one
INSERT INTO album_user_tags (id, user_id, album_id, tag)
VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, album_id, tag) DO UPDATE SET tag = tag
RETURNING id, user_id, album_id, tag, created_at
`

type CreateAlbumUserTagParams struct {
	ID      string
	UserID  string
	AlbumID string
	Tag     string
}

func (q *Queries) CreateAlbumUserTag(ctx context.Context, arg CreateAlbumUserTagParams) (AlbumUserTag, error) {
	row := q.db.QueryRowContext(ctx, createAlbumUserTag,
		arg.ID,
		arg.UserID,
		arg.AlbumID,
		arg.Tag,
	)
	var i AlbumUserTag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.Tag,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlbumGenresByAlbumId = `-- name: DeleteAlbumGenresByAlbumId :exec
DELETE FROM album_genres WHERE user_id = ? AND album_id = ?
`

type DeleteAlbumGenresByAlbumIdParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) DeleteAlbumGenresByAlbumId(ctx context.Context, arg DeleteAlbumGenresByAlbumIdParams) error {
	_, err := q.db.ExecContext(ctx, deleteAlbumGenresByAlbumId, arg.UserID, arg.AlbumID)
	return err
}

const deleteAlbumMoodsByAlbumId = `-- name: DeleteAlbumMoodsByAlbumId :exec
DELETE FROM album_moods WHERE user_id = ? AND album_id = ?
`

type DeleteAlbumMoodsByAlbumIdParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) DeleteAlbumMoodsByAlbumId(ctx context.Context, arg DeleteAlbumMoodsByAlbumIdParams) error {
	_, err := q.db.ExecContext(ctx, deleteAlbumMoodsByAlbumId, arg.UserID, arg.AlbumID)
	return err
}

const deleteAlbumUserTagsByAlbumId = `-- name: DeleteAlbumUserTagsByAlbumId :exec
DELETE FROM album_user_tags WHERE user_id = ? AND album_id = ?
`

type DeleteAlbumUserTagsByAlbumIdParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) DeleteAlbumUserTagsByAlbumId(ctx context.Context, arg DeleteAlbumUserTagsByAlbumIdParams) error {
	_, err := q.db.ExecContext(ctx, deleteAlbumUserTagsByAlbumId, arg.UserID, arg.AlbumID)
	return err
}

const getAlbumGenresByAlbumId = `-- name: GetAlbumGenresByAlbumId :many
SELECT id, user_id, album_id, genre_id, genre_label, created_at FROM album_genres WHERE user_id = ? AND album_id = ? ORDER BY genre_label
`

type GetAlbumGenresByAlbumIdParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) GetAlbumGenresByAlbumId(ctx context.Context, arg GetAlbumGenresByAlbumIdParams) ([]AlbumGenre, error) {
	rows, err := q.db.QueryContext(ctx, getAlbumGenresByAlbumId, arg.UserID, arg.AlbumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumGenre
	for rows.Next() {
		var i AlbumGenre
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.GenreID,
			&i.GenreLabel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlbumGenresByAlbumIds = `-- name: GetAlbumGenresByAlbumIds :many
SELECT id, user_id, album_id, genre_id, genre_label, created_at FROM album_genres WHERE user_id = ? AND album_id IN (/*SLICE:album_ids*/?) ORDER BY genre_label
`

type GetAlbumGenresByAlbumIdsParams struct {
	UserID   string
	AlbumIds []string
}

func (q *Queries) GetAlbumGenresByAlbumIds(ctx context.Context, arg GetAlbumGenresByAlbumIdsParams) ([]AlbumGenre, error) {
	query := getAlbumGenresByAlbumIds
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.AlbumIds) > 0 {
		for _, v := range arg.AlbumIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:album_ids*/?", strings.Repeat(",?", len(arg.AlbumIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:album_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumGenre
	for rows.Next() {
		var i AlbumGenre
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.GenreID,
			&i.GenreLabel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlbumMoodsByAlbumId = `-- name: GetAlbumMoodsByAlbumId :many
SELECT id, user_id, album_id, mood, created_at FROM album_moods WHERE user_id = ? AND album_id = ? ORDER BY mood
`

type GetAlbumMoodsByAlbumIdParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) GetAlbumMoodsByAlbumId(ctx context.Context, arg GetAlbumMoodsByAlbumIdParams) ([]AlbumMood, error) {
	rows, err := q.db.QueryContext(ctx, getAlbumMoodsByAlbumId, arg.UserID, arg.AlbumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumMood
	for rows.Next() {
		var i AlbumMood
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.Mood,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlbumMoodsByAlbumIds = `-- name: GetAlbumMoodsByAlbumIds :many
SELECT id, user_id, album_id, mood, created_at FROM album_moods WHERE user_id = ? AND album_id IN (/*SLICE:album_ids*/?) ORDER BY mood
`

type GetAlbumMoodsByAlbumIdsParams struct {
	UserID   string
	AlbumIds []string
}

func (q *Queries) GetAlbumMoodsByAlbumIds(ctx context.Context, arg GetAlbumMoodsByAlbumIdsParams) ([]AlbumMood, error) {
	query := getAlbumMoodsByAlbumIds
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.AlbumIds) > 0 {
		for _, v := range arg.AlbumIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:album_ids*/?", strings.Repeat(",?", len(arg.AlbumIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:album_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumMood
	for rows.Next() {
		var i AlbumMood
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.Mood,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlbumUserTagsByAlbumId = `-- name: GetAlbumUserTagsByAlbumId :many
SELECT id, user_id, album_id, tag, created_at FROM album_user_tags WHERE user_id = ? AND album_id = ? ORDER BY tag
`

type GetAlbumUserTagsByAlbumIdParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) GetAlbumUserTagsByAlbumId(ctx context.Context, arg GetAlbumUserTagsByAlbumIdParams) ([]AlbumUserTag, error) {
	rows, err := q.db.QueryContext(ctx, getAlbumUserTagsByAlbumId, arg.UserID, arg.AlbumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumUserTag
	for rows.Next() {
		var i AlbumUserTag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.Tag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlbumUserTagsByAlbumIds = `-- name: GetAlbumUserTagsByAlbumIds :many
SELECT id, user_id, album_id, tag, created_at FROM album_user_tags WHERE user_id = ? AND album_id IN (/*SLICE:album_ids*/?) ORDER BY tag
`

type GetAlbumUserTagsByAlbumIdsParams struct {
	UserID   string
	AlbumIds []string
}

func (q *Queries) GetAlbumUserTagsByAlbumIds(ctx context.Context, arg GetAlbumUserTagsByAlbumIdsParams) ([]AlbumUserTag, error) {
	query := getAlbumUserTagsByAlbumIds
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.AlbumIds) > 0 {
		for _, v := range arg.AlbumIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:album_ids*/?", strings.Repeat(",?", len(arg.AlbumIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:album_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumUserTag
	for rows.Next() {
		var i AlbumUserTag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.Tag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctUserMoods = `-- name: GetDistinctUserMoods :many
SELECT DISTINCT mood FROM album_moods WHERE user_id = ? ORDER BY mood
`

func (q *Queries) GetDistinctUserMoods(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctUserMoods, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var mood string
		if err := rows.Scan(&mood); err != nil {
			return nil, err
		}
		items = append(items, mood)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctUserTags = `-- name: GetDistinctUserTags :many
SELECT DISTINCT tag FROM album_user_tags WHERE user_id = ? ORDER BY tag
`

func (q *Queries) GetDistinctUserTags(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctUserTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
