// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/alecdray/wax/src/internal/core/db/models"
)

type Album struct {
	ID        string
	SpotifyID string
	Title     string
	CreatedAt time.Time
	DeletedAt sql.NullTime
	ImageUrl  sql.NullString
}

type AlbumArtist struct {
	AlbumID  string
	ArtistID string
}

type AlbumGenre struct {
	ID         string
	UserID     string
	AlbumID    string
	GenreID    string
	GenreLabel string
	CreatedAt  time.Time
}

type AlbumMood struct {
	ID        string
	UserID    string
	AlbumID   string
	Mood      string
	CreatedAt time.Time
}

type AlbumNote struct {
	ID        string
	UserID    string
	AlbumID   string
	Content   string
	UpdatedAt time.Time
}

type AlbumRatingLog struct {
	ID        string
	UserID    string
	AlbumID   string
	Rating    float64
	Note      sql.NullString
	CreatedAt time.Time
	State     sql.NullString
}

type AlbumRatingState struct {
	ID           string
	UserID       string
	AlbumID      string
	State        string
	SnoozeCount  int64
	NextRerateAt sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type AlbumTag struct {
	ID        string
	UserID    string
	AlbumID   string
	TagID     string
	CreatedAt time.Time
}

type AlbumTrack struct {
	AlbumID string
	TrackID string
}

type AlbumUserTag struct {
	ID        string
	UserID    string
	AlbumID   string
	Tag       string
	CreatedAt time.Time
}

type Artist struct {
	ID        string
	SpotifyID string
	Name      string
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type Feed struct {
	ID                  string
	UserID              string
	Kind                models.FeedKind
	CreatedAt           time.Time
	LastSyncCompletedAt sql.NullTime
	LastSyncStartedAt   sql.NullTime
	LastSyncStatus      models.FeedSyncStatus
}

type GooseDbVersion struct {
	ID        int64
	VersionID int64
	IsApplied int64
	Tstamp    sql.NullTime
}

type Release struct {
	ID        string
	AlbumID   string
	Format    models.ReleaseFormat
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type SqliteSequence struct {
	Name interface{}
	Seq  interface{}
}

type Tag struct {
	ID        string
	UserID    string
	Name      string
	GroupID   sql.NullString
	CreatedAt time.Time
}

type TagGroup struct {
	ID        string
	UserID    string
	Name      string
	CreatedAt time.Time
}

type Track struct {
	ID        string
	SpotifyID string
	Title     string
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type TrackPlay struct {
	ID       string
	UserID   string
	TrackID  string
	AlbumID  string
	PlayedAt time.Time
}

type User struct {
	ID                  string
	SpotifyID           string
	CreatedAt           time.Time
	DeletedAt           sql.NullTime
	SpotifyRefreshToken sql.NullString
}

type UserArtist struct {
	ID        string
	UserID    string
	ArtistID  string
	AddedAt   time.Time
	DeletedAt sql.NullTime
}

type UserRelease struct {
	ID        string
	UserID    string
	ReleaseID string
	AddedAt   time.Time
	DeletedAt sql.NullTime
	RemovedAt sql.NullTime
}

type UserTrack struct {
	ID        string
	UserID    string
	TrackID   string
	AddedAt   time.Time
	DeletedAt sql.NullTime
}
