// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const createAlbumTag = `-- name: CreateAlbumTag :one
INSERT INTO album_tags (id, user_id, album_id, tag_id) VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, album_id, tag_id) DO UPDATE SET tag_id = tag_id
RETURNING id, user_id, album_id, tag_id, created_at
`

type CreateAlbumTagParams struct {
	ID      string
	UserID  string
	AlbumID string
	TagID   string
}

func (q *Queries) CreateAlbumTag(ctx context.Context, arg CreateAlbumTagParams) (AlbumTag, error) {
	row := q.db.QueryRowContext(ctx, createAlbumTag,
		arg.ID,
		arg.UserID,
		arg.AlbumID,
		arg.TagID,
	)
	var i AlbumTag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.TagID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlbumTag = `-- name: DeleteAlbumTag :exec
DELETE FROM album_tags WHERE user_id = ? AND album_id = ? AND tag_id = ?
`

type DeleteAlbumTagParams struct {
	UserID  string
	AlbumID string
	TagID   string
}

func (q *Queries) DeleteAlbumTag(ctx context.Context, arg DeleteAlbumTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteAlbumTag, arg.UserID, arg.AlbumID, arg.TagID)
	return err
}

const deleteAlbumTagsByAlbumId = `-- name: DeleteAlbumTagsByAlbumId :exec
DELETE FROM album_tags WHERE user_id = ? AND album_id = ?
`

type DeleteAlbumTagsByAlbumIdParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) DeleteAlbumTagsByAlbumId(ctx context.Context, arg DeleteAlbumTagsByAlbumIdParams) error {
	_, err := q.db.ExecContext(ctx, deleteAlbumTagsByAlbumId, arg.UserID, arg.AlbumID)
	return err
}

const getAlbumTagsByAlbumId = `-- name: GetAlbumTagsByAlbumId :many
SELECT album_tags.album_id, tags.id, tags.user_id, tags.name, tags.group_id, tags.created_at,
    COALESCE(tag_groups.id, '') as group_id_value,
    COALESCE(tag_groups.name, '') as group_name
FROM album_tags
JOIN tags ON album_tags.tag_id = tags.id
LEFT JOIN tag_groups ON tags.group_id = tag_groups.id
WHERE album_tags.user_id = ? AND album_tags.album_id = ?
ORDER BY tags.name
`

type GetAlbumTagsByAlbumIdParams struct {
	UserID  string
	AlbumID string
}

type GetAlbumTagsByAlbumIdRow struct {
	AlbumID      string
	Tag          Tag
	GroupIDValue string
	GroupName    string
}

func (q *Queries) GetAlbumTagsByAlbumId(ctx context.Context, arg GetAlbumTagsByAlbumIdParams) ([]GetAlbumTagsByAlbumIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getAlbumTagsByAlbumId, arg.UserID, arg.AlbumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlbumTagsByAlbumIdRow
	for rows.Next() {
		var i GetAlbumTagsByAlbumIdRow
		if err := rows.Scan(
			&i.AlbumID,
			&i.Tag.ID,
			&i.Tag.UserID,
			&i.Tag.Name,
			&i.Tag.GroupID,
			&i.Tag.CreatedAt,
			&i.GroupIDValue,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlbumTagsByAlbumIds = `-- name: GetAlbumTagsByAlbumIds :many
SELECT album_tags.album_id, tags.id, tags.user_id, tags.name, tags.group_id, tags.created_at,
    COALESCE(tag_groups.id, '') as group_id_value,
    COALESCE(tag_groups.name, '') as group_name
FROM album_tags
JOIN tags ON album_tags.tag_id = tags.id
LEFT JOIN tag_groups ON tags.group_id = tag_groups.id
WHERE album_tags.user_id = ? AND album_tags.album_id IN (/*SLICE:album_ids*/?)
ORDER BY tags.name
`

type GetAlbumTagsByAlbumIdsParams struct {
	UserID   string
	AlbumIds []string
}

type GetAlbumTagsByAlbumIdsRow struct {
	AlbumID      string
	Tag          Tag
	GroupIDValue string
	GroupName    string
}

func (q *Queries) GetAlbumTagsByAlbumIds(ctx context.Context, arg GetAlbumTagsByAlbumIdsParams) ([]GetAlbumTagsByAlbumIdsRow, error) {
	query := getAlbumTagsByAlbumIds
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.AlbumIds) > 0 {
		for _, v := range arg.AlbumIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:album_ids*/?", strings.Repeat(",?", len(arg.AlbumIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:album_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlbumTagsByAlbumIdsRow
	for rows.Next() {
		var i GetAlbumTagsByAlbumIdsRow
		if err := rows.Scan(
			&i.AlbumID,
			&i.Tag.ID,
			&i.Tag.UserID,
			&i.Tag.Name,
			&i.Tag.GroupID,
			&i.Tag.CreatedAt,
			&i.GroupIDValue,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateTag = `-- name: GetOrCreateTag :one
INSERT INTO tags (id, user_id, name, group_id) VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, name) DO UPDATE SET name = name
RETURNING id, user_id, name, group_id, created_at
`

type GetOrCreateTagParams struct {
	ID      string
	UserID  string
	Name    string
	GroupID sql.NullString
}

func (q *Queries) GetOrCreateTag(ctx context.Context, arg GetOrCreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateTag,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.GroupID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.GroupID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateTagGroup = `-- name: GetOrCreateTagGroup :one
INSERT INTO tag_groups (id, user_id, name) VALUES (?, ?, ?)
ON CONFLICT (user_id, name) DO UPDATE SET name = name
RETURNING id, user_id, name, created_at
`

type GetOrCreateTagGroupParams struct {
	ID     string
	UserID string
	Name   string
}

func (q *Queries) GetOrCreateTagGroup(ctx context.Context, arg GetOrCreateTagGroupParams) (TagGroup, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateTagGroup, arg.ID, arg.UserID, arg.Name)
	var i TagGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getTagGroupsByUserId = `-- name: GetTagGroupsByUserId :many
SELECT id, user_id, name, created_at FROM tag_groups WHERE user_id = ?
`

func (q *Queries) GetTagGroupsByUserId(ctx context.Context, userID string) ([]TagGroup, error) {
	rows, err := q.db.QueryContext(ctx, getTagGroupsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TagGroup
	for rows.Next() {
		var i TagGroup
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsByUserId = `-- name: GetTagsByUserId :many
SELECT tags.id, tags.user_id, tags.name, tags.group_id, tags.created_at,
    COALESCE(tag_groups.id, '') as group_id_value,
    COALESCE(tag_groups.name, '') as group_name
FROM tags
LEFT JOIN tag_groups ON tags.group_id = tag_groups.id
WHERE tags.user_id = ?
ORDER BY tags.name
`

type GetTagsByUserIdRow struct {
	Tag          Tag
	GroupIDValue string
	GroupName    string
}

func (q *Queries) GetTagsByUserId(ctx context.Context, userID string) ([]GetTagsByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagsByUserIdRow
	for rows.Next() {
		var i GetTagsByUserIdRow
		if err := rows.Scan(
			&i.Tag.ID,
			&i.Tag.UserID,
			&i.Tag.Name,
			&i.Tag.GroupID,
			&i.Tag.CreatedAt,
			&i.GroupIDValue,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
