// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: track_plays.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const getLastPlayedAtByAlbumIds = `-- name: GetLastPlayedAtByAlbumIds :many
SELECT album_id, MAX(played_at) as last_played_at
FROM track_plays
WHERE user_id = ? AND album_id IN (/*SLICE:album_ids*/?)
GROUP BY album_id
`

type GetLastPlayedAtByAlbumIdsParams struct {
	UserID   string
	AlbumIds []string
}

type GetLastPlayedAtByAlbumIdsRow struct {
	AlbumID      string
	LastPlayedAt interface{}
}

func (q *Queries) GetLastPlayedAtByAlbumIds(ctx context.Context, arg GetLastPlayedAtByAlbumIdsParams) ([]GetLastPlayedAtByAlbumIdsRow, error) {
	query := getLastPlayedAtByAlbumIds
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.AlbumIds) > 0 {
		for _, v := range arg.AlbumIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:album_ids*/?", strings.Repeat(",?", len(arg.AlbumIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:album_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLastPlayedAtByAlbumIdsRow
	for rows.Next() {
		var i GetLastPlayedAtByAlbumIdsRow
		if err := rows.Scan(&i.AlbumID, &i.LastPlayedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentlyPlayedAlbums = `-- name: GetRecentlyPlayedAlbums :many
SELECT albums.id, albums.spotify_id, albums.title, albums.created_at, albums.deleted_at, albums.image_url, MAX(track_plays.played_at) as last_played_at,
    COALESCE((
        SELECT GROUP_CONCAT(a.name, ', ')
        FROM (SELECT DISTINCT ar.id, ar.name FROM album_artists aa JOIN artists ar ON ar.id = aa.artist_id WHERE aa.album_id = albums.id) AS a
    ), '') as artist_names,
    EXISTS (
        SELECT 1 FROM user_releases
        JOIN releases ON releases.id = user_releases.release_id
        WHERE releases.album_id = albums.id AND user_releases.user_id = track_plays.user_id AND user_releases.removed_at IS NULL
    ) as in_library
FROM track_plays
JOIN albums ON albums.id = track_plays.album_id
WHERE track_plays.user_id = ?
GROUP BY albums.id
ORDER BY last_played_at DESC
LIMIT 20
`

type GetRecentlyPlayedAlbumsRow struct {
	ID           string
	SpotifyID    string
	Title        string
	CreatedAt    time.Time
	DeletedAt    sql.NullTime
	ImageUrl     sql.NullString
	LastPlayedAt interface{}
	ArtistNames  interface{}
	InLibrary    int64
}

func (q *Queries) GetRecentlyPlayedAlbums(ctx context.Context, userID string) ([]GetRecentlyPlayedAlbumsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentlyPlayedAlbums, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentlyPlayedAlbumsRow
	for rows.Next() {
		var i GetRecentlyPlayedAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.Title,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.ImageUrl,
			&i.LastPlayedAt,
			&i.ArtistNames,
			&i.InLibrary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrackPlay = `-- name: UpsertTrackPlay :exec
INSERT INTO track_plays (id, user_id, track_id, album_id, played_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (user_id, track_id, played_at) DO NOTHING
`

type UpsertTrackPlayParams struct {
	ID       string
	UserID   string
	TrackID  string
	AlbumID  string
	PlayedAt time.Time
}

func (q *Queries) UpsertTrackPlay(ctx context.Context, arg UpsertTrackPlayParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrackPlay,
		arg.ID,
		arg.UserID,
		arg.TrackID,
		arg.AlbumID,
		arg.PlayedAt,
	)
	return err
}
