// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracks.sql

package sqlc

import (
	"context"
)

const createTrack = `-- name: CreateTrack :exec
INSERT INTO tracks (id, spotify_id, title, disc_number, track_number) VALUES (?, ?, ?, ?, ?)
`

type CreateTrackParams struct {
	ID          string
	SpotifyID   string
	Title       string
	DiscNumber  int64
	TrackNumber int64
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) error {
	_, err := q.db.ExecContext(ctx, createTrack,
		arg.ID,
		arg.SpotifyID,
		arg.Title,
		arg.DiscNumber,
		arg.TrackNumber,
	)
	return err
}

const getOrCreateTrack = `-- name: GetOrCreateTrack :one
INSERT INTO tracks (id, spotify_id, title, disc_number, track_number) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (spotify_id)
DO UPDATE SET disc_number = excluded.disc_number, track_number = excluded.track_number
RETURNING id, spotify_id, title, created_at, deleted_at, disc_number, track_number
`

type GetOrCreateTrackParams struct {
	ID          string
	SpotifyID   string
	Title       string
	DiscNumber  int64
	TrackNumber int64
}

func (q *Queries) GetOrCreateTrack(ctx context.Context, arg GetOrCreateTrackParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateTrack,
		arg.ID,
		arg.SpotifyID,
		arg.Title,
		arg.DiscNumber,
		arg.TrackNumber,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Title,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DiscNumber,
		&i.TrackNumber,
	)
	return i, err
}

const getTrack = `-- name: GetTrack :one
SELECT id, spotify_id, title, created_at, deleted_at, disc_number, track_number FROM tracks WHERE id = ?
`

func (q *Queries) GetTrack(ctx context.Context, id string) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrack, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Title,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DiscNumber,
		&i.TrackNumber,
	)
	return i, err
}

const getTrackBySpotifyId = `-- name: GetTrackBySpotifyId :one
SELECT id, spotify_id, title, created_at, deleted_at, disc_number, track_number FROM tracks WHERE spotify_id = ?
`

func (q *Queries) GetTrackBySpotifyId(ctx context.Context, spotifyID string) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrackBySpotifyId, spotifyID)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Title,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DiscNumber,
		&i.TrackNumber,
	)
	return i, err
}
