// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, spotify_id) VALUES (?, ?)
RETURNING id, spotify_id, created_at, deleted_at, spotify_refresh_token
`

type CreateUserParams struct {
	ID        string
	SpotifyID string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.SpotifyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SpotifyRefreshToken,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, spotify_id, created_at, deleted_at, spotify_refresh_token FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SpotifyRefreshToken,
	)
	return i, err
}

const getUserBySpotifyId = `-- name: GetUserBySpotifyId :one
SELECT id, spotify_id, created_at, deleted_at, spotify_refresh_token FROM users WHERE spotify_id = ?
`

func (q *Queries) GetUserBySpotifyId(ctx context.Context, spotifyID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySpotifyId, spotifyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SpotifyRefreshToken,
	)
	return i, err
}

const getUsersWithSpotifyToken = `-- name: GetUsersWithSpotifyToken :many
SELECT id, spotify_id, created_at, deleted_at, spotify_refresh_token FROM users
WHERE spotify_refresh_token IS NOT NULL AND deleted_at IS NULL
`

func (q *Queries) GetUsersWithSpotifyToken(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersWithSpotifyToken)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.SpotifyRefreshToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSpotifyUser = `-- name: UpsertSpotifyUser :one
INSERT INTO users (id, spotify_id, spotify_refresh_token) VALUES (?, ?, ?)
ON CONFLICT (spotify_id)
DO UPDATE SET spotify_id = EXCLUDED.spotify_id, spotify_refresh_token = coalesce(EXCLUDED.spotify_refresh_token, spotify_refresh_token)
RETURNING id, spotify_id, created_at, deleted_at, spotify_refresh_token
`

type UpsertSpotifyUserParams struct {
	ID                  string
	SpotifyID           string
	SpotifyRefreshToken sql.NullString
}

func (q *Queries) UpsertSpotifyUser(ctx context.Context, arg UpsertSpotifyUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertSpotifyUser, arg.ID, arg.SpotifyID, arg.SpotifyRefreshToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SpotifyRefreshToken,
	)
	return i, err
}
