// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_releases.sql

package sqlc

import (
	"context"
	"time"
)

const getUserReleases = `-- name: GetUserReleases :many
SELECT user_releases.id, user_releases.user_id, user_releases.release_id, user_releases.added_at, user_releases.deleted_at, user_releases.removed_at, releases.id, releases.album_id, releases.format, releases.created_at, releases.deleted_at, releases.discogs_id, releases.label, releases.released_at FROM user_releases
JOIN releases ON user_releases.release_id = releases.id
WHERE user_id = ? AND removed_at IS NULL
`

type GetUserReleasesRow struct {
	UserRelease UserRelease
	Release     Release
}

func (q *Queries) GetUserReleases(ctx context.Context, userID string) ([]GetUserReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserReleases, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserReleasesRow
	for rows.Next() {
		var i GetUserReleasesRow
		if err := rows.Scan(
			&i.UserRelease.ID,
			&i.UserRelease.UserID,
			&i.UserRelease.ReleaseID,
			&i.UserRelease.AddedAt,
			&i.UserRelease.DeletedAt,
			&i.UserRelease.RemovedAt,
			&i.Release.ID,
			&i.Release.AlbumID,
			&i.Release.Format,
			&i.Release.CreatedAt,
			&i.Release.DeletedAt,
			&i.Release.DiscogsID,
			&i.Release.Label,
			&i.Release.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserReleasesByAlbumId = `-- name: GetUserReleasesByAlbumId :many
SELECT user_releases.id, user_releases.user_id, user_releases.release_id, user_releases.added_at, user_releases.deleted_at, user_releases.removed_at, releases.id, releases.album_id, releases.format, releases.created_at, releases.deleted_at, releases.discogs_id, releases.label, releases.released_at FROM user_releases
JOIN releases ON user_releases.release_id = releases.id
WHERE user_id = ?
AND album_id = ?
AND removed_at IS NULL
`

type GetUserReleasesByAlbumIdParams struct {
	UserID  string
	AlbumID string
}

type GetUserReleasesByAlbumIdRow struct {
	UserRelease UserRelease
	Release     Release
}

func (q *Queries) GetUserReleasesByAlbumId(ctx context.Context, arg GetUserReleasesByAlbumIdParams) ([]GetUserReleasesByAlbumIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserReleasesByAlbumId, arg.UserID, arg.AlbumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserReleasesByAlbumIdRow
	for rows.Next() {
		var i GetUserReleasesByAlbumIdRow
		if err := rows.Scan(
			&i.UserRelease.ID,
			&i.UserRelease.UserID,
			&i.UserRelease.ReleaseID,
			&i.UserRelease.AddedAt,
			&i.UserRelease.DeletedAt,
			&i.UserRelease.RemovedAt,
			&i.Release.ID,
			&i.Release.AlbumID,
			&i.Release.Format,
			&i.Release.CreatedAt,
			&i.Release.DeletedAt,
			&i.Release.DiscogsID,
			&i.Release.Label,
			&i.Release.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUserRelease = `-- name: SoftDeleteUserRelease :exec
UPDATE user_releases
SET removed_at = current_timestamp
WHERE user_id = ? AND release_id = ? AND removed_at IS NULL
`

type SoftDeleteUserReleaseParams struct {
	UserID    string
	ReleaseID string
}

func (q *Queries) SoftDeleteUserRelease(ctx context.Context, arg SoftDeleteUserReleaseParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteUserRelease, arg.UserID, arg.ReleaseID)
	return err
}

const softDeleteUserReleasesByAlbumId = `-- name: SoftDeleteUserReleasesByAlbumId :exec
UPDATE user_releases
SET removed_at = current_timestamp
WHERE user_id = ? AND release_id IN (
    SELECT id FROM releases WHERE album_id = ?
)
`

type SoftDeleteUserReleasesByAlbumIdParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) SoftDeleteUserReleasesByAlbumId(ctx context.Context, arg SoftDeleteUserReleasesByAlbumIdParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteUserReleasesByAlbumId, arg.UserID, arg.AlbumID)
	return err
}

const upsertUserRelease = `-- name: UpsertUserRelease :one
INSERT INTO user_releases (id, user_id, release_id, added_at) VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, release_id)
DO UPDATE SET
    added_at = EXCLUDED.added_at,
    removed_at = NULL
RETURNING id, user_id, release_id, added_at, deleted_at, removed_at
`

type UpsertUserReleaseParams struct {
	ID        string
	UserID    string
	ReleaseID string
	AddedAt   time.Time
}

func (q *Queries) UpsertUserRelease(ctx context.Context, arg UpsertUserReleaseParams) (UserRelease, error) {
	row := q.db.QueryRowContext(ctx, upsertUserRelease,
		arg.ID,
		arg.UserID,
		arg.ReleaseID,
		arg.AddedAt,
	)
	var i UserRelease
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReleaseID,
		&i.AddedAt,
		&i.DeletedAt,
		&i.RemovedAt,
	)
	return i, err
}
