// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_album_radar.sql

package sqlc

import (
	"context"
)

const addAlbumToRadar = `-- name: AddAlbumToRadar :one
INSERT INTO user_album_radar (id, user_id, album_id)
VALUES (?, ?, ?)
ON CONFLICT (user_id, album_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id, user_id, album_id, created_at
`

type AddAlbumToRadarParams struct {
	ID      string
	UserID  string
	AlbumID string
}

// Idempotent: if a radar row exists, it's returned unchanged.
func (q *Queries) AddAlbumToRadar(ctx context.Context, arg AddAlbumToRadarParams) (UserAlbumRadar, error) {
	row := q.db.QueryRowContext(ctx, addAlbumToRadar, arg.ID, arg.UserID, arg.AlbumID)
	var i UserAlbumRadar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.CreatedAt,
	)
	return i, err
}

const getRadarAlbums = `-- name: GetRadarAlbums :many
SELECT user_album_radar.id, user_album_radar.user_id, user_album_radar.album_id, user_album_radar.created_at, albums.id, albums.spotify_id, albums.title, albums.created_at, albums.deleted_at, albums.image_url
FROM user_album_radar
JOIN albums ON user_album_radar.album_id = albums.id
WHERE user_album_radar.user_id = ?
  AND NOT EXISTS (
      SELECT 1 FROM user_releases ur
      JOIN releases r ON r.id = ur.release_id
      WHERE ur.user_id = user_album_radar.user_id
        AND r.album_id = user_album_radar.album_id
  )
`

type GetRadarAlbumsRow struct {
	UserAlbumRadar UserAlbumRadar
	Album          Album
}

// Returns radar rows whose album has no user_releases entries (not on wishlist, not owned, not removed).
// This enforces the "any release activity wipes radar" invariant at query time.
func (q *Queries) GetRadarAlbums(ctx context.Context, userID string) ([]GetRadarAlbumsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRadarAlbums, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRadarAlbumsRow
	for rows.Next() {
		var i GetRadarAlbumsRow
		if err := rows.Scan(
			&i.UserAlbumRadar.ID,
			&i.UserAlbumRadar.UserID,
			&i.UserAlbumRadar.AlbumID,
			&i.UserAlbumRadar.CreatedAt,
			&i.Album.ID,
			&i.Album.SpotifyID,
			&i.Album.Title,
			&i.Album.CreatedAt,
			&i.Album.DeletedAt,
			&i.Album.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isAlbumOnRadar = `-- name: IsAlbumOnRadar :one
SELECT EXISTS (
    SELECT 1 FROM user_album_radar
    WHERE user_id = ? AND album_id = ?
) AS on_radar
`

type IsAlbumOnRadarParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) IsAlbumOnRadar(ctx context.Context, arg IsAlbumOnRadarParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isAlbumOnRadar, arg.UserID, arg.AlbumID)
	var on_radar int64
	err := row.Scan(&on_radar)
	return on_radar, err
}

const removeAlbumFromRadar = `-- name: RemoveAlbumFromRadar :exec
DELETE FROM user_album_radar
WHERE user_id = ? AND album_id = ?
`

type RemoveAlbumFromRadarParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) RemoveAlbumFromRadar(ctx context.Context, arg RemoveAlbumFromRadarParams) error {
	_, err := q.db.ExecContext(ctx, removeAlbumFromRadar, arg.UserID, arg.AlbumID)
	return err
}
